### ISSUE TITLE
There appears to be no [open source] license that is assigned to this project (like Apache2) ?

### ISSUE THREAD

**Issue by rbygrave** [Shabirmean/vscode-ebean-enhancement-ext#10]
Are you happy to apply an open source license to this project (like apache2) ?  This would then allow others to fork and maintain the project going forward if you were ok with that?

Thanks, Rob.

Note: I am one of the maintainers of Ebean ORM so have that interest in seeing if we can maintain this going forward.

**Comment by Shabirmean** [comment]
Thank you very much. Extremely sorry for the extremely delayed response. 

I just added a LICENSE to the project enabling others to fork and build on top of it. 

Thank you.
